var provincesSelectOption = [
  { label: "آذربایجان شرقی", value: "آذربایجان شرقی" },
  { label: "آذربایجان غربی", value: "آذربایجان غربی" },
  { label: "اردبیل", value: "اردبیل" },
  { label: "اصفهان", value: "اصفهان" },
  { label: "البرز", value: "البرز" },
  { label: "ایلام", value: "ایلام" },
  { label: "بوشهر", value: "بوشهر" },
  { label: "تهران", value: "تهران" },
  { label: "چهارمحال و بختیاری", value: "چهارمحال و بختیاری" },
  { label: "خراسان جنوبی", value: "خراسان جنوبی" },
  { label: "خراسان رضوی", value: "خراسان رضوی" },
  { label: "خراسان شمالی", value: "خراسان شمالی" },
  { label: "خوزستان", value: "خوزستان" },
  { label: "زنجان", value: "زنجان" },
  { label: "سمنان", value: "سمنان" },
  { label: "سیستان و بلوچستان", value: "سیستان و بلوچستان" },
  { label: "فارس", value: "فارس" },
  { label: "قزوین", value: "قزوین" },
  { label: "قم", value: "قم" },
  { label: "كردستان", value: "كردستان" },
  { label: "كرمان", value: "كرمان" },
  { label: "كرمانشاه", value: "كرمانشاه" },
  { label: "كهكیلویه و بویراحمد", value: "كهكیلویه و بویراحمد" },
  { label: "گلستان", value: "گلستان" },
  { label: "گیلان", value: "گیلان" },
  { label: "لرستان", value: "لرستان" },
  { label: "مازندران", value: "مازندران" },
  { label: "مركزی", value: "مركزی" },
  { label: "هرمزگان", value: "هرمزگان" },
  { label: "همدان", value: "همدان" },
  { label: "یزد", value: "یزد" },
];

export default provincesSelectOption;
